// <auto-generated />
using MakeupRetailSearcher.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MakeupRetailSearcher.Migrations
{
    [DbContext(typeof(MakeupContext))]
    partial class MakeupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakeupRetailSearcher.Models.Makeup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<int>("Price");

                    b.Property<int>("Product_Id");

                    b.Property<string>("Product_Name");

                    b.Property<int>("Retailer_Id");

                    b.Property<string>("Type");

                    b.HasKey("id");

                    b.ToTable("Makeup");
                });
#pragma warning restore 612, 618
        }
    }
}
